In [2]:
#np.random.rand() – Random float numbers between 0 and 1

import numpy as np

np.random.seed(42) # For reproducibility

a=np.random.rand(3)
print("Random float values between 0 and 1:", a)

Random float values between 0 and 1: [0.37454012 0.95071431 0.73199394]


In [3]:
#np.random.randint() – Random integers in a given range
b=np.random.randint(0,10,size=5)
print("Random integers between 0 and 9:", b)

Random integers between 0 and 9: [4 6 9 2 6]


In [4]:
#np.random.randn() – Random samples from a normal distribution
c=np.random.randn(3)

print("Random numbers from standard normal distribution:", c)


Random numbers from standard normal distribution: [ 1.57921282  0.76743473 -0.46947439]


In [5]:
#np.random.shuffle() – Shuffle an existing array in-place

arr=np.arange(5)
print("Original array is:",arr)
np.random.shuffle(arr)

print("Shuffled array is:",arr)


Original array is: [0 1 2 3 4]
Shuffled array is: [2 1 4 0 3]


In [6]:
#reshape() – Change the shape of the array without changing data
a=np.arange(6)
reshape=a.reshape((2,3))

print("Original Array:",a)
print("Reshaped array:",reshape)

Original Array: [0 1 2 3 4 5]
Reshaped array: [[0 1 2]
 [3 4 5]]


In [7]:
#ravel() vs flatten()
#ravel() returns a view of the original array (changes reflect back)
#flatten() returns a copy (independent array)

b=np.array([[1,2],[3,4]])
r=b.ravel()
f=b.flatten()

print("Original:\n",b)
print("Ravelled:\n",r)
print("Flatten:\n",f)

b[0][0]=100
print("\nAfter modifying b[0][0]:")
print("Ravelled reflects change:\n", r)
print("Flattened stays same:\n", f)

Original:
 [[1 2]
 [3 4]]
Ravelled:
 [1 2 3 4]
Flatten:
 [1 2 3 4]

After modifying b[0][0]:
Ravelled reflects change:
 [100   2   3   4]
Flattened stays same:
 [1 2 3 4]


In [8]:
#transpose() – Flips rows to columns (used in matrices)
c=np.array([[1,2,3],[4,5,6]])
print("Original array before transpose:\n",c)
print("Original array after transpose:\n",c.T)

Original array before transpose:
 [[1 2 3]
 [4 5 6]]
Original array after transpose:
 [[1 4]
 [2 5]
 [3 6]]


In [9]:
import numpy as np

d = np.array([[1, 2], [3, 4]])
print("Original shape:", d.shape)
print("Original array:\n", d)

swapped = np.swapaxes(d, 0, 1)
print("Swapped axes (0 and 1): shape", swapped.shape)
print("Swapped array:\n", swapped)


Original shape: (2, 2)
Original array:
 [[1 2]
 [3 4]]
Swapped axes (0 and 1): shape (2, 2)
Swapped array:
 [[1 3]
 [2 4]]


In [10]:
#vstack() & hstack() – Stack arrays vertically or horizontally
a=np.array([1,2])
b=np.array([3,4])

v=np.vstack((a,b))
h=np.hstack((a,b))

print("Vertical Stack:\n", v)
print("Horizontal Stack:\n", h)

Vertical Stack:
 [[1 2]
 [3 4]]
Horizontal Stack:
 [1 2 3 4]


In [11]:
#split() – Split arrays into multiple parts
a=np.array([1,2,3,4,5,6])
splits=np.split(a,3)

print("Original array:", a)
print("Splitted into 3 parts:", splits)


Original array: [1 2 3 4 5 6]
Splitted into 3 parts: [array([1, 2]), array([3, 4]), array([5, 6])]


In [12]:
#: Set Operations in NumPy
a = np.array([1, 2, 3, 4])
b = np.array([3, 4, 5, 6])

print("Union:",np.union1d(a,b))
print("Intersection:",np.intersect1d(a,b))
print("Set Difference:",np.setdiff1d(a,b))
print("Symettric Difference:",np.setxor1d(a,b))

Union: [1 2 3 4 5 6]
Intersection: [3 4]
Set Difference: [1 2]
Symettric Difference: [1 2 5 6]


In [13]:
#View – Shares data with original (changes reflect)
#Copy – Independent

a=np.array([1,2,3])
view_arr=a.view()
copy_arr=a.copy()

a[0] = 99
print("Original:", a)
print("View reflects change:", view_arr)
print("Copy stays unchanged:", copy_arr)

Original: [99  2  3]
View reflects change: [99  2  3]
Copy stays unchanged: [1 2 3]


In [14]:
#Optional Challenges
import numpy as np

# 1. Create a random 3x3 matrix of integers (0 to 9)
matrix = np.random.randint(0, 10, size=(3, 3))
print(" Random 3x3 Matrix:\n", matrix)

# 2. Flatten it
flattened = matrix.flatten()
print("\n Flattened Matrix (1D array):\n", flattened)

# 3. Transpose it (does it change?)
transposed = flattened.T
print("\n Transposed Flattened Array:\n", transposed)

# Check shape
print("Shape of flattened:", flattened.shape)
print("Shape of transposed:", transposed.shape)
#  Transposing a 1D array does nothing since there's only 1 axis.

# 4. Stack it with another array (horizontal and vertical)
another_array = np.arange(9)
print("\n Another Array to Stack:\n", another_array)

# Reshape both to 2D before stacking
flat_2d = flattened.reshape(1, -1)
another_2d = another_array.reshape(1, -1)

# Horizontal Stack
h_stack = np.hstack((flat_2d, another_2d))
print("\n Horizontally Stacked Arrays:\n", h_stack)

# Vertical Stack
v_stack = np.vstack((flat_2d, another_2d))
print("\n Vertically Stacked Arrays:\n", v_stack)

# 5. Find intersection with another array
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([3, 4, 5, 6, 7])
intersection = np.intersect1d(array1, array2)
print("\n Intersection of Arrays:\n", intersection)

# 6. Demonstrate Copy vs View
original = np.array([10, 20, 30])
view = original.view()
copy = original.copy()

# Change the view
view[0] = 999
print("\n Original after modifying view:\n", original)
print(" View:\n", view)

# Change the copy
copy[1] = 888
print("\n Copy after modification (original unaffected):\n", copy)
print(" Original (unchanged by copy):\n", original)


 Random 3x3 Matrix:
 [[9 5 8]
 [0 9 2]
 [6 3 8]]

 Flattened Matrix (1D array):
 [9 5 8 0 9 2 6 3 8]

 Transposed Flattened Array:
 [9 5 8 0 9 2 6 3 8]
Shape of flattened: (9,)
Shape of transposed: (9,)

 Another Array to Stack:
 [0 1 2 3 4 5 6 7 8]

 Horizontally Stacked Arrays:
 [[9 5 8 0 9 2 6 3 8 0 1 2 3 4 5 6 7 8]]

 Vertically Stacked Arrays:
 [[9 5 8 0 9 2 6 3 8]
 [0 1 2 3 4 5 6 7 8]]

 Intersection of Arrays:
 [3 4 5]

 Original after modifying view:
 [999  20  30]
 View:
 [999  20  30]

 Copy after modification (original unaffected):
 [ 10 888  30]
 Original (unchanged by copy):
 [999  20  30]
