In [1]:
#Basic Mathematical Operations
import numpy as np

a=np.array([1,2,3])
b=np.array([4,5,6])

print(a+b) #Element wise addition
print(a-b) #Element wise subtraction
print(a*b) #Element wise multiplication
print(a/b) #Element wise divison


[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [2]:
#Boolean Indexing

arr=np.array([10,20,30,40,50])
bool_idr= arr>25 #Creates Boolean

print(bool_idr)
print(arr[bool_idr])




[False False  True  True  True]
[30 40 50]


In [3]:
#Fancy Indexing
x=np.array([100,200,300,400,500,600])

indices=[1,2,3]

print(x[indices])

[200 300 400]


In [4]:
#Conditional Replacement
a=np.array([1,2,3,4,5])
a[a>3]=99

print(a)


[ 1  2  3 99 99]


In [5]:
#Aggregation Functions

b=np.array([[1,2],[3,4]])

print(np.sum(b))

print(np.sum(b,axis=0)) #Column wise addition

print(np.sum(b,axis=1))#Row wise addition

print(np.max(b))
print(np.min(b))
      


10
[4 6]
[3 7]
4
1
