In [1]:
import numpy as np

In [2]:
#Creating Arrays
#From python list

a=np.array([1,2,3])
b=np.array([[1,2],[3,4]])

#Predefined zeros
zeros=np.zeros((2,3))
ones=np.ones((3,3))
eye=np.eye(3)
arange=np.arange(0,10,1)
linspace=np.linspace(0,1,5)



In [3]:
print(a)
print(b)
print(zeros)
print(ones)
print(eye)
print(arange)
print(linspace)


[1 2 3]
[[1 2]
 [3 4]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[0 1 2 3 4 5 6 7 8 9]
[0.   0.25 0.5  0.75 1.  ]


In [4]:
#Array Attributes
print("Shape:",a.shape)
print("DataType:",a.dtype)
print("Dimensions:",a.ndim)
print("Size:",a.size)



Shape: (3,)
DataType: int32
Dimensions: 1
Size: 3


In [5]:
#Indexing and Slicing
arr= np.array([[1,2,3],[4,5,6]])
print(arr[0,1])
print(arr[:1])
print(arr[1,:])


2
[[1 2 3]]
[4 5 6]


In [6]:
#Basic Operation
x=np.array([1,2,3])
y=np.array([4,5,6])

print(x+y)
print(x*y)
print(x/2)
print(x**2)


[5 7 9]
[ 4 10 18]
[0.5 1.  1.5]
[1 4 9]


In [7]:
#Broadcasting
a=np.array([[1],[2],[3]])
b=np.array([10,20,30])
print(a+b)



[[11 21 31]
 [12 22 32]
 [13 23 33]]


In [8]:
#Practice Exercise

#Create a 2D array of shape (3, 4) filled with 7s.
arr=np.full((3,4),7)
print(arr)

#Create a NumPy array from 1 to 100 and reshape to (10, 10)

x=np.arange(1,101).reshape((10,10))
print(x)

#Slice out the 2nd and 3rd rows from a 4x4 array
y=np.arange(16).reshape(4,4)
sliced=y[1:3,:]
print(sliced)

# Multiply two arrays using broadcasting
a=np.array([[1],[2],[3]])
b=np.array([10,20,30])

results=a*b
print(results)

#Find the mean, median, and standard deviation of a given array
z=np.array([1,2,3,4,5])
mean=np.mean(z)
median=np.median(z)
std=np.std(z)
print(mean)
print(median)
print(std)



[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]
[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]
[[ 4  5  6  7]
 [ 8  9 10 11]]
[[10 20 30]
 [20 40 60]
 [30 60 90]]
3.0
3.0
1.4142135623730951
